package dev.gerard.signalharbor.analytics;

import dev.gerard.signalharbor.config.SignalHarborProperties;
import dev.gerard.signalharbor.signal.ServiceSignal;
import dev.gerard.signalharbor.signal.ServiceSignalRepository;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

/**
 * PATTERN: Strategy (implementation pattern)
 *
 * RiskScoringService is the Context. It delegates score computation to a
 * RiskScoringStrategy, making it easy to swap algorithms (weighted sums,
 * spike detection, ML-based) without modifying this class (OCP).
 *
 * Default strategy: WeightedRiskScoringStrategy (injected by Spring).
 * Override at startup by qualifying a different bean.
 */
@Service
public class RiskScoringService {
    private final ServiceSignalRepository signalRepository;
    private final SignalHarborProperties properties;
    private final Clock clock;
    private final Counter summariesGenerated;
    private final RiskScoringStrategy scoringStrategy;

    @Autowired
    public RiskScoringService(
            ServiceSignalRepository signalRepository,
            SignalHarborProperties properties,
            MeterRegistry meterRegistry,
            @Qualifier("weightedRiskScoringStrategy") RiskScoringStrategy scoringStrategy
    ) {
        this(signalRepository, properties, Clock.systemUTC(), meterRegistry, scoringStrategy);
    }

    RiskScoringService(
            ServiceSignalRepository signalRepository,
            SignalHarborProperties properties,
            Clock clock,
            MeterRegistry meterRegistry,
            RiskScoringStrategy scoringStrategy
    ) {
        this.signalRepository = signalRepository;
        this.properties = properties;
        this.clock = clock;
        this.scoringStrategy = scoringStrategy;
        this.summariesGenerated = Counter.builder("signal-harbor.risk.summaries.generated")
                .description("Risk summaries generated by service name")
                .register(meterRegistry);
    }

    @Cacheable(value = "riskSummaries", key = "#serviceName.toLowerCase()")
    public RiskSummary summarize(String serviceName) {
        Instant windowEnd = clock.instant();
        Instant windowStart = windowEnd.minus(Duration.ofHours(properties.riskLookbackHours()));
        List<ServiceSignal> signals = signalRepository.findByServiceNameIgnoreCaseAndObservedAtAfter(
                serviceName,
                windowStart
        );

        int score = scoringStrategy.computeScore(signals);
        Map<String, Long> signalsByType = signals.stream()
                .collect(Collectors.groupingBy(signal -> signal.getSignalType().name(), Collectors.counting()));

        summariesGenerated.increment();
        return new RiskSummary(
                serviceName,
                windowStart,
                windowEnd,
                signals.size(),
                score,
                scoringStrategy.toLevel(score),
                signalsByType
        );
    }

    /** Kept for backward-compat with existing tests; delegates to strategy default. */
    RiskLevel toRiskLevel(int score) {
        return scoringStrategy.toLevel(score);
    }
}
